services:
  - type: web
    name: analysisdoc-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: "4000"
      - key: DB_USER
        value: ZDgyMMC3Dgevt8t.root
      - key: DB_PASSWORD
        value: obRjHNoDGY9x4XoO
      - key: DB_NAME
        value: test
      - key: OPENROUTER_API_KEY
        value: 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
      - key: PRODUCTION
        value: "true"
